export const toPayData = {
    userName: "Akshay",
    userAvatar: "https://via.placeholder.com/150",
    userStatus: "online",
    userGreeting: "Hi, Akshay",
    userGreetingMessage: "Let's see how much you owe",
    userAmountToPay: 1200,
    userAmountToPayMessage: "Total amount you owe to all people",
    userPaymentRecords: [
        {
            id: 1,
            name: "John Doe",
            amount: 100,
            borrowedDate: "2024-01-15",
            category: "Personal loan",
            status: "unpaid",
            remaining: 100,
            avatar: "https://via.placeholder.com/150",
        },
        {
            id: 2,
            name: "Sarah Wilson",
            amount: 75.5,
            borrowedDate: "2024-02-01",
            category: "Dinner",
            status: "paid",
            remaining: 75.5,
            avatar: "https://via.placeholder.com/150",
        },
        {
            id: 3,
            name: "Sarah Wilson",
            amount: 75.5,
            borrowedDate: "2024-02-01",
            category: "Dinner",
            status: "partial",
            remaining: 75.5,
            avatar: "https://via.placeholder.com/150",
            trx_history: [
                {
                    id: 1,
                    amount: 100,
                    date: "2024-01-15",
                },
                {
                    id: 2,
                    amount: 100,
                    date: "2024-01-15",
                },
                {
                    id: 3,
                    amount: 100,
                    date: "2024-01-15",
                },
            ],
        },
        {
            id: 4,
            name: "Sarand",
            amount: 750,
            borrowedDate: "2024-02-01",
            category: "Dinner and Akshay",
            status: "overdue",
            remaining: 75.5,
            avatar: "https://via.placeholder.com/150",
            trx_history: [
                {
                    id: 1,
                    amount: 750,
                    date: "2024-01-15",
                },
            ],
        },
    ],
};
